// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3646pWdbtDdNomq5Sd6xeZGzoE1JZoy8',
    appId: '1:894547244965:android:c308b52844345976585a4c',
    messagingSenderId: '894547244965',
    projectId: 'sensors-25d65',
    databaseURL: 'https://sensors-25d65-default-rtdb.firebaseio.com',
    storageBucket: 'sensors-25d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD12QalKGplQaqaqxDb3iWEXi6bC07ynQ',
    appId: '1:894547244965:ios:e83bc6bdd1189fdc585a4c',
    messagingSenderId: '894547244965',
    projectId: 'sensors-25d65',
    databaseURL: 'https://sensors-25d65-default-rtdb.firebaseio.com',
    storageBucket: 'sensors-25d65.appspot.com',
    iosBundleId: 'mx.edu.utch.rtdata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrTZ4QDnjCKedLNoTQikeEifo53t_i9Dk',
    appId: '1:894547244965:web:a20c1cea588a46f5585a4c',
    messagingSenderId: '894547244965',
    projectId: 'sensors-25d65',
    authDomain: 'sensors-25d65.firebaseapp.com',
    databaseURL: 'https://sensors-25d65-default-rtdb.firebaseio.com',
    storageBucket: 'sensors-25d65.appspot.com',
  );
}
